name: Python application

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при PR в ветку main

jobs:
  test:
    runs-on: ubuntu-latest  # Используется последняя версия Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Клонируем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Укажите версию Python, которая используется

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Обновление pip
          pip install -r requirements.txt  # Установка зависимостей

      - name: Run tests
        run: |
          pytest  # Запуск тестов с использованием pytest
